#!/bin/sh

#
# Grep multiple files in the current directory and subdirectories.
# The filtering is to exclude files you probably don't want to grep
#
# http://github.com/simonbaird/personal/blob/master/findgrep
#
# Usage:
#  findgrep needle           # look for needle
#  findgrep -i neEdle        # case insensitive
#  findgrep needle '*.php'   # only look in php files
#

if [ ".$1" = ".-i" ]; then
	NO_CASE=$1
	AWK_NO_CASE='-vIGNORECASE=1'
	shift;
fi

SEARCH_TERM=$1
FIND_IN_FILES=$2

if [ "~$FIND_IN_FILES" != '~' ]; then
	FIND_IN_FILES="-iname $FIND_IN_FILES"
fi

SEARCH_TERM_COLOR='\033[0;31m'
FILE_NAME_COLOR='\033[0;33m'
LINE_NUMBER_COLOR='\033[0;34m'
COLOR_OFF='\033[0m'

find . \
	-name ".bzr" -prune -o \
	-name ".svn" -prune -o \
	-name ".git" -prune -o \
	-name "phpdoc" -prune -o \
	! -iname "*.gz" \
	! -iname "*.~?~" \
	! -iname "*~" \
	! -iname "._*" \
	! -iname ".Trashes" \
	! -iname ".Spotlight-*" \
	! -iname "*.tgz" \
	! -iname "*.zip" \
	! -iname "*.swp" \
	! -iname "*.pdf" \
	! -iname "*.gif" \
	! -iname "*.jpg" \
	! -iname "*.png" \
	! -iname "*.ttf" \
	$FIND_IN_FILES \
	-exec \
		grep -n $NO_CASE "$SEARCH_TERM" /dev/null {} \; \
			| awk -F':' -vORS='' $AWK_NO_CASE "{
				print \"$FILE_NAME_COLOR\" \$1 \"$COLOR_OFF:\"
				print \"$LINE_NUMBER_COLOR\" \$2 \"$COLOR_OFF:\"
				text = substr(\$0,length(\$1\$2)+3)
				gsub(/$SEARCH_TERM/, \"$SEARCH_TERM_COLOR&$COLOR_OFF\", text)
				print text \"\n\"
			}"

