#!/bin/sh

#
# Grep multiple files in the current directory and subdirectories.
# The filtering is to exclude files you probably don't want to grep
#
# Usage:
#  findgrep needle
#

SEARCH_TERM_COLOR='[0;31m'
FILE_NAME_COLOR='[0;33m'
LINE_NUMBER_COLOR='[0;34m'
COLOR_OFF='[0m'

SEARCH_TERM=$1
GREP_ARGS=$2
FIND_ARGS=$3


find . \
    -name ".bzr" -prune -o \
    -name ".svn" -prune -o \
    -name ".git" -prune -o \
    ! -iname "*.gz" \
    ! -iname "*.~?~" \
    ! -iname "._*" \
    ! -iname ".Trashes" \
    ! -iname ".Spotlight-*" \
    ! -iname "*.tgz" \
    ! -iname "*.zip" \
    ! -iname "*.swp" \
    ! -iname "*.pdf" \
    ! -iname "*.gif" \
    ! -iname "*.jpg" \
    ! -iname "*.png" \
    ! -iname "*.ttf" \
	$FIND_ARGS \
    -exec grep -n $GREP_ARGS "$SEARCH_TERM" /dev/null {} \; \
		| sed "s/\\($SEARCH_TERM\\)/${SEARCH_TERM_COLOR}\\1${COLOR_OFF}/ig" \
		| sed "s/^\\([^:]*\\):\\([^:]*\\):/${FILE_NAME_COLOR}\\1${COLOR_OFF}:${LINE_NUMBER_COLOR}\\2${COLOR_OFF}:/"

